include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI app for OAF
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+appfilter +kmod-oaf +luci-compat +luci-lib-jsonc

PKG_NAME:=luci-app-oaf
PKG_VERSION:=7.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
